name: Build and Deploy Documentation

on:
  push:
  pull_request:

jobs:
  build-documentation:
    name: Build and deploy cFS documents
    uses: nasa/cFS/.github/workflows/build-deploy-doc.yml@main
    with:
      target: "[\"ds-usersguide\"]"
      app-name: ds
      buildpdf: ${{ github.event_name == 'push' && contains(github.ref, 'main')}}
      deploy: ${{ github.event_name == 'push' && contains(github.ref, 'main')}}
